stages:
  - build
  - deploy

build:
  stage: build
  image: ghcr.io/cirruslabs/flutter:stable
  script:
    - flutter pub get
    - flutter build web
  artifacts:
    paths:
      - build/web

pages:
  stage: deploy
  script:
    - mv build/web public
  artifacts:
    paths:
      - public
  only:
    - main