// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi57icTIUL_Zr_-EHfj2IFPPx20W3-0zw',
    appId: '1:174859643162:web:ff12e208993b58729c64a3',
    messagingSenderId: '174859643162',
    projectId: 'messageapp-b584c',
    authDomain: 'messageapp-b584c.firebaseapp.com',
    storageBucket: 'messageapp-b584c.firebasestorage.app',
    measurementId: 'G-F3DKLV92EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBGX5R7QjnaaUK1nmK1v_044NHrO8PDcQ',
    appId: '1:174859643162:android:451d0e2e7bcb3b6a9c64a3',
    messagingSenderId: '174859643162',
    projectId: 'messageapp-b584c',
    storageBucket: 'messageapp-b584c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw2xQJDIZLDdiHh0ROvKss8klyRTukNyM',
    appId: '1:174859643162:ios:790b43ea8d38982d9c64a3',
    messagingSenderId: '174859643162',
    projectId: 'messageapp-b584c',
    storageBucket: 'messageapp-b584c.firebasestorage.app',
    iosClientId: '174859643162-8idu8c0shlkh6f83mvbhavhutq345rh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw2xQJDIZLDdiHh0ROvKss8klyRTukNyM',
    appId: '1:174859643162:ios:790b43ea8d38982d9c64a3',
    messagingSenderId: '174859643162',
    projectId: 'messageapp-b584c',
    storageBucket: 'messageapp-b584c.firebasestorage.app',
    iosClientId: '174859643162-8idu8c0shlkh6f83mvbhavhutq345rh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi57icTIUL_Zr_-EHfj2IFPPx20W3-0zw',
    appId: '1:174859643162:web:9e892ea98f2444b49c64a3',
    messagingSenderId: '174859643162',
    projectId: 'messageapp-b584c',
    authDomain: 'messageapp-b584c.firebaseapp.com',
    storageBucket: 'messageapp-b584c.firebasestorage.app',
    measurementId: 'G-JKYSKQFQ9H',
  );
}
